#!/bin/bash
which node >/dev/null 2>&1 || (echo "node must be installed to use this script" && return 1)
which npm >/dev/null 2>&1 || (echo "npm must be installed to use this script" && return 1)
npm ci
